kind: pipeline
name: web_staging
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: docker 
  image: plugins/docker
  settings:
    dockerfile: docker/staging/web/Dockerfile
    repo: quay.io/natlibfi/finto-suggestions-web
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
name: api_staging
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: docker 
  image: plugins/docker
  settings:
    dockerfile: docker/staging/api/Dockerfile
    repo: quay.io/natlibfi/finto-suggestions-api
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
