kind: pipeline
name: web_staging
steps:
  - name: docker
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/finto-suggestions-web
    tag: staging
    dockerfile: /drone/src/docker/staging/web/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    when:
      event: push
      branch: [master, fix/backend-performance-fixing]

---
kind: pipeline
name: api_staging
steps:
  - name: docker
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/finto-suggestions-api
    tag: staging
    dockerfile: /drone/src/docker/staging/api/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    when:
      event: push
      branch: [master, fix/backend-performance-fixing]
