pipeline:
  # web:
  #   image: plugins/docker
  #   repo: quay.io/repository/natlibfi/finto-suggestions
  #   dockerfile: ./docker/web/Dockerfile
  # api:
  #   image: plugins/docker
  #   repo: quay.io/repository/natlibfi/finto-suggestions
  #   dockerfile: ./docker/api/Dockerfile
  docker:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/repository/natlibfi/finto-suggestions
    dockerfile: ./docker/web/Dockerfile
    dockerfile: ./docker/api/Dockerfile
    when:
      event: [push]
      branch: [feature/drone-pipeline-testing]