pipeline:
  web:
    image: plugins/docker
    registry: quay.io
    repo: natlibfi/finto-suggestions/
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    tag: latest
    dockerfile: ./docker/web/Dockerfile
    when:
      event: push
      branch: feature/drone-pipeline-testing
  api:
    image: plugins/docker
    registry: quay.io
    repo: natlibfi/finto-suggestions/
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    tag: latest
    dockerfile: ./docker/api/Dockerfile
    when:
      event: push
      branch: feature/drone-pipeline-testing