pipeline:
  web:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/finto-suggestions-web
    secrets:
      - docker_username
      - docker_password
    tag: latest
    dockerfile: ./docker/web/Dockerfile
    when:
      event: push
      branch: feature/drone-pipeline-testing
  api:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/finto-suggestions-api
    secrets:
      - docker_username
      - docker_password
    tag: latest
    dockerfile: ./docker/api/Dockerfile
    when:
      event: push
      branch: feature/drone-pipeline-testing