pipeline:
  web:
    group: build
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/finto-suggestions-web
    secrets:
      - docker_username
      - docker_password
    tag: latest
    dockerfile: ./docker/staging/web/Dockerfile
    when:
      event: push
      branch: [master, feature/staging-build]
  api:
    group: build
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/finto-suggestions-api
    secrets:
      - docker_username
      - docker_password
    tag: latest
    dockerfile: ./docker/staging/api/Dockerfile
    when:
      event: push
      branch: [master, feature/staging-build]