pipeline:
  web:
    image: plugins/docker
    repo: quay.io/repository/natlibfi/finto-suggestions/
    tag: latest
    dockerfile: ./docker/web/Dockerfile
    when:
      event: push
      branch: feature/drone-pipeline-testing
  api:
    image: plugins/docker
    repo: quay.io/repository/natlibfi/finto-suggestions/
    tag: latest
    dockerfile: ./docker/api/Dockerfile
    when:
      event: push
      branch: feature/drone-pipeline-testing