version: '3.6'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/develop/web/Dockerfile
    image: finto-suggestions_web:latest
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - network_web
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/develop/api/Dockerfile
    image: finto-suggestions_api:latest
    volumes:
      - ./api:/app
    env_file: .env
    networks:
      - network_web
      - network_db
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/develop/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network_web
    depends_on:
      - api
      - web
  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - volume_db:/var/lib/postgresql/data
    command: ["postgres", "-c", "logging_collector=on"]
    command: ["postgres", "-c", "log_statement=all"]
    #command: ["postgres", "-c", "log_directory=/logs"]
    #command: ["postgres", "-c", "log_filename=postgresql.log"]
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - network_db
networks:
  network_db:
    driver: bridge
  network_web:
    driver: bridge
volumes:
  volume_db:
