version: '3.6'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/app
    environment:
      - APP_SECRET_KEY=changethis
      - APP_CONFIG_OBJECT=config.DevelopmentConfig
      - FLASK_APP=wsgi:flask_app
    networks:
      - network_web
      - network_db
    depends_on:
      - db
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - network_web
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network_web
    depends_on:
      - api
      - web
  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - volume_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=psdb
    ports:
      - 5432:5432
    networks:
      - network_db
networks:
  network_db:
    driver: bridge
  network_web:
    driver: bridge
volumes:
  volume_db:
