const NEWEST_FIRST = 'CREATED_DESC';
const OLDEST_FIRST = 'CREATED_ASC';
const MOST_COMMENTS = 'COMMENTS_DESC';
const LEAST_COMMENTS = 'COMMENTS_ASC';
const LAST_UPDATED = 'UPDATED_DESC';
const MOST_REACTIONS = 'REACTIONS_DESC';

export default {
  NEWEST_FIRST,
  OLDEST_FIRST,
  MOST_COMMENTS,
  LEAST_COMMENTS,
  LAST_UPDATED,
  MOST_REACTIONS
};
