"""Adds column 'color' to tags

Revision ID: 013e63f2ff49
Revises: 8d6e87fab399
Create Date: 2019-07-14 22:21:39.494094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013e63f2ff49'
down_revision = '8d6e87fab399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    # ### end Alembic commands ###
