"""Sets suggestions table status not nullable

Revision ID: 01e91259577c
Revises: 61fa3cf3732a
Create Date: 2019-02-13 08:58:57.168840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01e91259577c'
down_revision = '1ce8294d773d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestions', 'status',
               existing_type=postgresql.ENUM('RECEIVED', 'READ ', 'REJECTED', 'ACCEPTED', 'RETAINED', 'ARCHIVED', name='suggestionstatustypes'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestions', 'status',
               existing_type=postgresql.ENUM('RECEIVED', 'READ ', 'REJECTED', 'ACCEPTED', 'RETAINED', 'ARCHIVED', name='suggestionstatustypes'),
               nullable=True)
    # ### end Alembic commands ###
