"""add event_id to suggestion_tags_association that relations events table

Revision ID: 2ebfe25cf572
Revises: e008d81a779e
Create Date: 2018-11-12 06:04:29.367803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebfe25cf572'
down_revision = 'e008d81a779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion_tags_association', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suggestion_tags_association', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggestion_tags_association', type_='foreignkey')
    op.drop_column('suggestion_tags_association', 'event_id')
    # ### end Alembic commands ###
