"""Add new field yse_term to suggestion table. Yse_term is used to link suggestion to yse.

Revision ID: 61fa3cf3732a
Revises: 6c8aa3d470ce
Create Date: 2019-02-06 13:44:39.612259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fa3cf3732a'
down_revision = '6c8aa3d470ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('yse_term', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'yse_term')
    # ### end Alembic commands ###
