"""Add new field to user table (title, organization and imageurl)

Revision ID: 6c8aa3d470ce
Revises: 6716392d2909
Create Date: 2019-01-26 09:29:34.989773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8aa3d470ce'
down_revision = '6716392d2909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imageUrl', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'imageUrl')
    # ### end Alembic commands ###
