"""Allows suggestion status to be null

Revision ID: e6f353653628
Revises: 01e91259577c
Create Date: 2019-03-19 23:10:25.774167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6f353653628'
down_revision = '01e91259577c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestions', 'status',
               existing_type=postgresql.ENUM('RECEIVED', 'READ', 'REJECTED', 'ACCEPTED', 'RETAINED', 'ARCHIVED', name='suggestionstatustypes'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestions', 'status',
               existing_type=postgresql.ENUM('RECEIVED', 'READ', 'REJECTED', 'ACCEPTED', 'RETAINED', 'ARCHIVED', name='suggestionstatustypes'),
               nullable=False)
    # ### end Alembic commands ###
