"""Edit suggestion table columns to be samekind of by widget that can create new suggestions

Revision ID: ee5b145411ae
Revises: 579817d6ce82
Create Date: 2018-12-20 13:11:29.247662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee5b145411ae'
down_revision = '579817d6ce82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('alternative_labels', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('suggestions', sa.Column('broader_labels', sa.JSON(), nullable=True))
    op.add_column('suggestions', sa.Column('exactMatches', sa.JSON(), nullable=True))
    op.add_column('suggestions', sa.Column('groups', sa.JSON(), nullable=True))
    op.add_column('suggestions', sa.Column('narrower_labels', sa.JSON(), nullable=True))
    op.add_column('suggestions', sa.Column('neededFor', sa.String(length=500), nullable=True))
    op.add_column('suggestions', sa.Column('related_labels', sa.JSON(), nullable=True))
    op.add_column('suggestions', sa.Column('scopeNote', sa.Text(), nullable=True))
    op.drop_column('suggestions', 'broader')
    op.drop_column('suggestions', 'group')
    op.drop_column('suggestions', 'alternative_label')
    op.drop_column('suggestions', 'narrower')
    op.drop_column('suggestions', 'related')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('related', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suggestions', sa.Column('narrower', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suggestions', sa.Column('alternative_label', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suggestions', sa.Column('group', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suggestions', sa.Column('broader', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('suggestions', 'scopeNote')
    op.drop_column('suggestions', 'related_labels')
    op.drop_column('suggestions', 'neededFor')
    op.drop_column('suggestions', 'narrower_labels')
    op.drop_column('suggestions', 'groups')
    op.drop_column('suggestions', 'exactMatches')
    op.drop_column('suggestions', 'broader_labels')
    op.drop_column('suggestions', 'alternative_labels')
    # ### end Alembic commands ###
